---
- hosts: personal-server
  become: true
  tasks:
  - name: install docker deps
    apt:
      update_cache: true
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

  - name: add docker repo
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
      state: present
      update_cache: yes

  - name: install docker
    apt:
      update_cache: true
      name: docker-ce

  - name: copy nginx dir
    copy:
      src: ../nginx-server
      dest: /home/ubuntu/

  - name: copy node dir
    copy:
      src: ../node-server
      dest: /home/ubuntu/

  - name: copy python dir
    copy:
      src: ../python-server
      dest: /home/ubuntu/
