---
- hosts: personal-server
  become: true
  tasks:
  - name: install docker deps
    apt:
      update_cache: true
      name: "{{ packages }}"
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-pip

  - name: add docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present

  - name: add docker repo
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
      state: present
      update_cache: yes

  - name: install docker
    apt:
      update_cache: true
      name: docker-ce

  - name: install docker-py # For ansible usage
    pip:
      name: docker-py

  - name: copy nginx dir
    copy:
      src: ../nginx-server
      dest: /home/ubuntu/

  - name: run docker nginx image
    docker_container: # https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#docker-container-module
      name: nginx
      image: nginx
      ports: "8080:80"

  - name: copy node dir
    copy:
      src: ../node-server
      dest: /home/ubuntu/

  - name: copy python dir
    copy:
      src: ../python-server
      dest: /home/ubuntu/
